# -*- coding: utf-8 -*-
"""DATA ANALYST Task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ycLa0DtjHLgX8P3IdMAaSc-uhjwIzPET
"""

# Importing Required Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Importing Data

df = pd.read_csv('/content/supermarket_sales - Sheet1.csv')
df.head()

df.info()

df.shape

#Checking Missing values
df.isnull().sum()

# Remove duplicate rows
df.drop_duplicates(inplace=True)

df.duplicated()

Invoice_ID = range(1, 1001)
df['Invoice ID'] = Invoice_ID

# Standardize text values
df['Gender'] = df['Gender'].str.lower()  # Convert to lowercase
df['City'] = df['City'].str.title()  # Title case for city names
df['Customer type'] = df['Customer type'].str.capitalize()  # Capitalize customer type

df.head()

# Convert date formats to a consistent type
df['Date'] = pd.to_datetime(df['Date'], format='%m/%d/%Y').dt.strftime('%d-%m-%Y')

# Rename column headers to be clean and uniform
df.columns = df.columns.str.lower().str.replace(' ', '_')

# Check data types
print(df.dtypes)

# Fix data types if necessary
# For example, ensure 'Quantity' is an integer
df['quantity'] = df['quantity'].astype(int)

# Ensure 'Date' is in datetime format
df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')

